pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your code from your version control system (e.g., Git)
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Add build steps here
                sh 'npm install'  // Example: Install npm dependencies
                sh 'ng build --prod'  // Example: Build your Angular app
            }
        }

        stage('Test') {
            steps {
                // Add test steps here
                sh 'npm test'  // Example: Run tests
            }
        }

        stage('Deploy') {
            steps {
                // Add deployment steps here
                sh 'npm deploy'  // Example: Deploy your app
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
