pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your code from your version control system (e.g., Git)
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Add build steps here
                sh 'npm install'  // Example: Install npm dependencies
            }
        }

       

        stage('run') {
            steps {
                // Add deployment steps here    
                sh 'ng serve'  // Example: Deploy your app
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
