pipeline {
    agent {
        label 'your-agent-label'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'ng build --prod'
            }
        }
        stage('Deploy') {
            steps {
                // Use your deployment method here (e.g., deploy to a web server, AWS S3, etc.)
                // For example, you can copy the build artifacts to a server.
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
